#certpem = "auto"
#keypem = ""
#basedir = "./web/static"
#addr = "localhost:443"
#addrext = "https://localhost/"
#user = "sam"
#password = "samantha"
[salon]
picturefsimage = "./salon/embed/pfsEmbed/salon-digital.png"
picturefsjson = "./salon/embed/pfsEmbed/salon-digital.json"
staticdir = "./salon/embed/static"
templatedir = "./salon/embed/template/template"
templatedev = true
bleveindex = "c:/temp/bangbang/bangbang.bleve"
