#certpem = "auto"
#keypem = ""
#basedir = "./web/static"
#addr = "localhost:443"
#addrext = "https://localhost/"
#user = "sam"
#password = "samantha"
picturedir = "./pfsEmbed"
staticdir = "./web/static"
templatedir = "./web/template"
templatedev = true